version: "3.3"

services:
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "${ACME_FILE_PATH}:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

  # N8N (https://github.com/n8n-io/n8n)
  n8n:
    extends:
      file: apps/n8n/docker-compose.yml
      service: n8n

  # Vaultwarden (https://github.com/dani-garcia/vaultwarden)
  vaultwarden:
    extends:
      file: apps/vaultwarden/docker-compose.yml
      service: vaultwarden

  # Plausible (https://github.com/plausible/analytics)
  plausible:
    extends:
      file: apps/plausible/docker-compose.yml
      service: plausible
  plausible_db:
    extends:
      file: apps/plausible/docker-compose.yml
      service: plausible_db
  plausible_events_db:
    extends:
      file: apps/plausible/docker-compose.yml
      service: plausible_events_db

