version: "3.3"

services:
  n8n:
    image: n8nio/n8n
    container_name: "n8n"
    env_file: ".env"
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.n8n.loadBalancer.server.port=5678"
      - "traefik.http.routers.n8n.rule=Host(`n8n.${BASE_DOMAIN}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
    volumes:
      - ".n8n:/home/node/.n8n"
      