version: "3.3"

services:
  pghero:
    image: ankane/pghero
    container_name: "pghero"
    env_file: ".env"
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pghero.loadBalancer.server.port=8080"
      - "traefik.http.routers.pghero.rule=Host(`pghero.${BASE_DOMAIN}`)"
      - "traefik.http.routers.pghero.entrypoints=websecure"
      - "traefik.http.routers.pghero.tls.certresolver=myresolver"
      